<h3>Imports and Setup</h3>

In [11]:
import pandas as pd
import numpy as np

In [12]:
pd.set_option('display.max_columns', None)

In [35]:
big_table = pd.read_csv('data/T_T100_SEGMENT_ALL_CARRIER.csv')
area_codes_table = pd.read_csv('data/L_WORLD_AREA_CODES.csv')
carrier_classes = pd.read_csv('data/L_CARRIER_GROUP_NEW.csv')

In [58]:
# Replace World Area Codes (WAC) with descriptions from lookup table
big_table = big_table.merge(area_codes_table, left_on='DEST_WAC', right_on='Code', how='left')
big_table['DEST_WAC'] = big_table['Description']
big_table['ORIGIN_WAC'] = big_table['Description']
big_table = big_table.drop(columns=['Code', 'Description'])

In [59]:
big_table

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,REGION,CARRIER,CARRIER_NAME,CARRIER_GROUP_NEW,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,ORIGIN_COUNTRY_NAME,ORIGIN_WAC,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_NM,DEST_COUNTRY_NAME,DEST_WAC,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,NEW,New England Airlines Inc.,D,NEW,New England Airlines Inc.,6,30613,BID,"Block Island, RI",Rhode Island,United States,Rhode Island,35855,WST,"Westerly, RI",Rhode Island,United States,Rhode Island,0,79,1,2024,1,1,1,F,DU
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,NEW,New England Airlines Inc.,D,NEW,New England Airlines Inc.,6,30613,BID,"Block Island, RI",Rhode Island,United States,Rhode Island,35855,WST,"Westerly, RI",Rhode Island,United States,Rhode Island,0,79,1,2024,3,7,1,F,DU
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,NEW,New England Airlines Inc.,D,NEW,New England Airlines Inc.,6,35855,WST,"Westerly, RI",Rhode Island,United States,Rhode Island,30613,BID,"Block Island, RI",Rhode Island,United States,Rhode Island,0,79,1,2024,1,1,1,F,DU
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,NEW,New England Airlines Inc.,D,NEW,New England Airlines Inc.,6,35855,WST,"Westerly, RI",Rhode Island,United States,Rhode Island,30613,BID,"Block Island, RI",Rhode Island,United States,Rhode Island,0,79,1,2024,3,7,1,F,DU
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,0.0,0.0,9K,Cape Air,D,9K,Cape Air,6,33541,MVY,"Martha's Vineyard, MA",Massachusetts,United States,Massachusetts,32250,HYA,"Hyannis, MA",Massachusetts,United States,Massachusetts,1,125,1,2024,1,1,1,F,DU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314502,891.0,889.0,2367000.0,8002.0,4689.0,5250.0,0.0,59.0,33895.0,26497.0,GV,Grant Aviation,D,GV,Grant Aviation,5,31555,ENA,"Kenai, AK",Alaska,United States,Alaska,30299,ANC,"Anchorage, AK",Alaska,United States,Alaska,4,416,1,2024,2,6,1,F,DU
314503,995.0,994.0,2737200.0,8946.0,7247.0,10718.0,0.0,59.0,37921.0,27463.0,GV,Grant Aviation,D,GV,Grant Aviation,5,30299,ANC,"Anchorage, AK",Alaska,United States,Alaska,31555,ENA,"Kenai, AK",Alaska,United States,Alaska,4,416,1,2024,3,7,1,F,DU
314504,999.0,998.0,2748200.0,8991.0,6631.0,5663.0,0.0,59.0,39218.0,30137.0,GV,Grant Aviation,D,GV,Grant Aviation,5,31555,ENA,"Kenai, AK",Alaska,United States,Alaska,30299,ANC,"Anchorage, AK",Alaska,United States,Alaska,4,416,1,2024,3,7,1,F,DU
314505,1522.0,1522.0,1826400.0,8026.0,5084.0,10340.0,0.0,11.0,17768.0,13202.0,S2,Star Marianas Air Inc.,D,S2,Star Marianas Air Inc.,6,35215,TIQ,"Tinian, TT",U.S. Pacific Trust Territories and Possessions,United States,U.S. Pacific Trust Territories and Possessions,34955,SPN,"Saipan, TT",U.S. Pacific Trust Territories and Possessions,United States,U.S. Pacific Trust Territories and Possessions,0,79,1,2024,3,7,1,F,DU
314506,1574.0,1574.0,1888800.0,8284.0,5104.0,29100.0,0.0,11.0,20390.0,15668.0,S2,Star Marianas Air Inc.,D,S2,Star Marianas Air Inc.,6,34955,SPN,"Saipan, TT",U.S. Pacific Trust Territories and Possessions,United States,U.S. Pacific Trust Territories and Possessions,35215,TIQ,"Tinian, TT",U.S. Pacific Trust Territories and Possessions,United States,U.S. Pacific Trust Territories and Possessions,0,79,1,2024,3,7,1,F,DU

<h3>Filter Major Carriers</h3>

In [41]:
carrier_classes

   Code                                        Description
0     0                                   Foreign Carriers
1     1  Large Regional Carriers (carriers with annual ...
2     2  National Carriers (carriers with annual revenu...
3     3  Major Carriers (carriers with annual revenue o...
4     4  Medium Regional Carriers (carriers with annual...
5     5  Small Certificated Carriers (carrier holding c...
6     6  Commuter Carriers (air taxi operator which per...
7     7  All Cargo Carriers operating under cerificates...
8     9  Commuter Carriers (Air Taxi providing Essentia...

In [63]:
# Filter only major carriers (TranStats category 3)
major_carriers = big_table.loc[big_table['CARRIER_GROUP_NEW'] == 3]
major_carriers['CARRIER_NAME'].unique()

array(['Delta Air Lines Inc.', 'USA Jet Airlines Inc.',
       'United Air Lines Inc.', 'Republic Airline', 'JetBlue Airways',
       'Hawaiian Airlines Inc.', 'Allegiant Air', 'Alaska Airlines Inc.',
       'Southwest Airlines Co.', 'American Airlines Inc.',
       'Sun Country Airlines d/b/a MN Airlines', 'Atlas Air Inc.',
       'Federal Express Corporation', 'Polar Air Cargo Airways',
       'Kalitta Air LLC', 'Spirit Air Lines', 'SkyWest Airlines Inc.',
       'Envoy Air', 'Frontier Airlines Inc.', 'United Parcel Service'],
      dtype=object)

In [78]:
# Filter passenger flights only
major_passenger_flights = major_carriers.loc[major_carriers['PASSENGERS'] > 0]
major_passenger_flights['CARRIER_NAME'].unique()

array(['United Air Lines Inc.', 'Republic Airline', 'JetBlue Airways',
       'Delta Air Lines Inc.', 'Hawaiian Airlines Inc.', 'Allegiant Air',
       'Alaska Airlines Inc.', 'Southwest Airlines Co.',
       'American Airlines Inc.', 'Sun Country Airlines d/b/a MN Airlines',
       'Atlas Air Inc.', 'SkyWest Airlines Inc.', 'Envoy Air',
       'Spirit Air Lines', 'Frontier Airlines Inc.'], dtype=object)

In [80]:
major_passenger_flights = major_passenger_flights[major_passenger_flights['DEPARTURES_PERFORMED'] > 0]
major_passenger_flights

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,REGION,CARRIER,CARRIER_NAME,CARRIER_GROUP_NEW,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,ORIGIN_COUNTRY_NAME,ORIGIN_WAC,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_NM,DEST_COUNTRY_NAME,DEST_WAC,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
16954,0.0,1.0,10592.0,126.0,39.0,0.0,0.0,151.0,82.0,31.0,UA,United Air Lines Inc.,D,UA,United Air Lines Inc.,3,30849,BZN,"Bozeman, MT",Montana,United States,Wyoming,32441,JAC,"Jackson, WY",Wyoming,United States,Wyoming,6,698,1,2024,1,2,1,F,DU
17533,0.0,1.0,19085.0,126.0,89.0,0.0,0.0,1781.0,353.0,282.0,UA,United Air Lines Inc.,D,UA,United Air Lines Inc.,3,34945,STT,"Charlotte Amalie, VI",U.S. Virgin Islands,United States,Louisiana,33495,MSY,"New Orleans, LA",Louisiana,United States,Louisiana,6,612,1,2024,2,4,4,F,DU
17534,0.0,1.0,19092.0,70.0,23.0,0.0,0.0,926.0,252.0,217.0,YX,Republic Airline,D,YX,Republic Airline,3,33198,MCI,"Kansas City, MO",Missouri,United States,Virginia,30852,IAD,"Washington, DC",Virginia,United States,Virginia,6,677,1,2024,3,7,2,F,DU
17535,0.0,1.0,19092.0,70.0,37.0,0.0,0.0,268.0,135.0,109.0,YX,Republic Airline,D,YX,Republic Airline,3,30198,PIT,"Pittsburgh, PA",Pennsylvania,United States,Pennsylvania,34100,PHL,"Philadelphia, PA",Pennsylvania,United States,Pennsylvania,6,677,1,2024,2,5,1,F,DU
17536,0.0,1.0,19092.0,70.0,38.0,0.0,0.0,726.0,141.0,123.0,YX,Republic Airline,D,YX,Republic Airline,3,30198,PIT,"Pittsburgh, PA",Pennsylvania,United States,Minnesota,31650,MSP,"Minneapolis, MN",Minnesota,United States,Minnesota,6,677,1,2024,1,1,2,F,DU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314480,651.0,640.0,20245300.0,81920.0,61880.0,318384.0,0.0,100.0,26638.0,14115.0,HA,Hawaiian Airlines Inc.,D,HA,Hawaiian Airlines Inc.,3,32134,HNL,"Honolulu, HI",Hawaii,United States,Hawaii,33830,OGG,"Kahului, HI",Hawaii,United States,Hawaii,6,608,1,2024,1,1,1,F,DU
314481,652.0,626.0,19819100.0,80128.0,61372.0,52167.0,0.0,100.0,28326.0,17411.0,HA,Hawaiian Airlines Inc.,D,HA,Hawaiian Airlines Inc.,3,33830,OGG,"Kahului, HI",Hawaii,United States,Hawaii,32134,HNL,"Honolulu, HI",Hawaii,United States,Hawaii,6,608,1,2024,2,5,1,F,DU
314482,654.0,640.0,20244900.0,81920.0,59510.0,56945.0,0.0,100.0,29282.0,15820.0,HA,Hawaiian Airlines Inc.,D,HA,Hawaiian Airlines Inc.,3,33830,OGG,"Kahului, HI",Hawaii,United States,Hawaii,32134,HNL,"Honolulu, HI",Hawaii,United States,Hawaii,6,608,1,2024,1,1,1,F,DU
314483,656.0,647.0,20482000.0,82816.0,67276.0,332314.0,0.0,100.0,27420.0,14326.0,HA,Hawaiian Airlines Inc.,D,HA,Hawaiian Airlines Inc.,3,32134,HNL,"Honolulu, HI",Hawaii,United States,Hawaii,33830,OGG,"Kahului, HI",Hawaii,United States,Hawaii,6,608,1,2024,3,7,1,F,DU
314484,657.0,646.0,20451000.0,82688.0,63763.0,61433.0,0.0,100.0,26942.0,15613.0,HA,Hawaiian Airlines Inc.,D,HA,Hawaiian Airlines Inc.,3,33830,OGG,"Kahului, HI",Hawaii,United States,Hawaii,32134,HNL,"Honolulu, HI",Hawaii,United States,Hawaii,6,608,1,2024,3,7,1,F,DU